"""``hardpoint doctor``: turn first-hour failures into a checklist.

Most first-hour failures in a tool like this are environmental -- a key not
exported, an extra not installed, an index created with another model's width,
a vector store that is not running -- and each surfaces, unaided, as a
confusing exception at the worst moment. ``doctor`` looks for all of them up
front and prints what to do about each (ARCHITECTURE.md §26.1).

Checks, in order: secret hygiene, configuration and environment, version skew,
every component resolves (missing extras), indexes reachable, embedding and
index dimensions agree, sources exist, the pipeline factory builds.

It spends no money: nothing is embedded or generated unless ``--live`` asks.
"""

import re
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import hardpoint
from hardpoint.cli.commands.project import CliState, load_project_config
from hardpoint.core.config.loader import ResolvedConfig
from hardpoint.core.config.schema import ComponentSpec, HardpointConfig
from hardpoint.core.errors import (
    ConfigError,
    HardpointError,
    InvalidRequestError,
    MissingEnvironmentVariableError,
)
from hardpoint.core.registry import ComponentRegistry, Kind
from hardpoint.runtime.resources import Resources, build_resources, build_source, load_pipeline

__all__ = ["Check", "component_checks", "configured_components", "render_checks", "run_doctor"]

Status = Literal["ok", "warn", "fail"]

# A key whose name says "secret" holding something other than an ${env:...}
# reference, or a value shaped like a well-known credential wherever it appears.
# Matched on the name's ending, so `token_budget` and `max_tokens` are not keys.
_KEY_VALUE = re.compile(r"^\s*-?\s*(?P<key>[\w.-]+)\s*:\s*(?P<value>.+?)\s*$")
_SECRET_SUFFIXES = ("api_key", "apikey", "secret", "secret_key", "password", "passwd", "token")
_CREDENTIAL = re.compile(
    r"(sk-[A-Za-z0-9_-]{16,}|AKIA[0-9A-Z]{16}|ghp_[A-Za-z0-9]{30,}|xox[bp]-[A-Za-z0-9-]{10,})"
)
_SAFE_VALUE = re.compile(r"""^(["']?)(\$\{env:[^}]+\}|null|~|""|''|)\1$""")


@dataclass(frozen=True)
class Check:
    """One line of the doctor's report."""

    name: str
    status: Status
    detail: str = ""
    remedy: str = ""


def _secret_hygiene(config_dir: Path) -> list[Check]:
    """Fail when a literal credential appears in any YAML under ``config/``.

    Secrets come only from ``${env:...}`` (ARCHITECTURE.md §19), because a key
    committed in YAML is a key published.
    """
    findings: list[str] = []
    for path in sorted(config_dir.glob("*.y*ml")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            stripped = line.split("#", 1)[0]
            match = _KEY_VALUE.match(stripped)
            if (
                match
                and match.group("key").lower().endswith(_SECRET_SUFFIXES)
                and not _SAFE_VALUE.match(match.group("value"))
            ):
                findings.append(f"{path}:{number}: {match.group('key')} has a literal value")
            elif _CREDENTIAL.search(stripped):
                findings.append(f"{path}:{number}: a value looks like a credential")
    if not findings:
        return [Check("secret hygiene", "ok", "no literal credentials in config/")]
    return [
        Check(
            "secret hygiene",
            "fail",
            "\n".join(findings),
            "Replace each literal with `${env:NAME}` and put the value in `.env` or the "
            "environment. Rotate any key that was ever committed.",
        )
    ]


def _version_skew(config: HardpointConfig) -> Check:
    """Warn when the project was generated by a release with another major.minor."""
    recorded = config.project.hardpoint_version
    installed = hardpoint.__version__
    if recorded is None:
        return Check("version", "ok", f"hardpoint {installed}")
    if recorded.split(".")[:2] == installed.split(".")[:2]:
        return Check("version", "ok", f"project {recorded}, installed {installed}")
    return Check(
        "version",
        "warn",
        f"project generated with {recorded}, installed {installed}",
        "Read the migration notes in CHANGELOG.md between the two versions, then "
        "update `project.hardpoint_version`. `hardpoint init <dir> --diff` shows what a "
        "fresh template would change.",
    )


def configured_components(config: HardpointConfig) -> list[tuple[Kind, str, ComponentSpec]]:
    """Every configured component, with its kind and config path."""
    found: list[tuple[Kind, str, ComponentSpec]] = []
    providers = config.providers
    for kind, path, spec in (
        (Kind.LLM, "providers.llm", providers.llm),
        (Kind.EMBEDDINGS, "providers.embeddings", providers.embeddings),
        (Kind.RERANKER, "providers.reranker", providers.reranker),
        (Kind.STATE, "ingestion.state", config.ingestion.state),
        (Kind.TRACER, "observability.tracer", config.observability.tracer),
        (Kind.METRICS, "observability.metrics", config.observability.metrics),
    ):
        if spec is not None:
            found.append((kind, path, spec))
            if spec.policies.fallback is not None:
                found.append((kind, f"{path}.policies.fallback", spec.policies.fallback))
    found.extend((Kind.INDEX, f"indexes.{n}", s) for n, s in sorted(config.indexes.items()))
    found.extend((Kind.SOURCE, f"sources.{n}", s) for n, s in sorted(config.sources.items()))
    return found


def component_checks(config: HardpointConfig, registry: ComponentRegistry) -> list[Check]:
    """Resolve every configured component, which is where a missing extra surfaces."""
    checks: list[Check] = []
    for kind, path, spec in configured_components(config):
        try:
            registration = registry.resolve(kind, spec.type, config_path=f"{path}.type")
            registry.validate_options(registration, spec.options(), config_path=path)
        except ConfigError as exc:
            checks.append(Check(f"component {path}", "fail", exc.message, exc.remedy or ""))
        else:
            checks.append(Check(f"component {path}", "ok", f"{kind.value} {spec.type!r}"))
    return checks


async def _live_checks(res: Resources) -> list[Check]:
    """Reachability, dimensions, sources and the pipeline, against built components."""
    checks: list[Check] = []
    config = res.config
    await res.state.initialise()

    for name, index in sorted(res.indexes.items()):
        try:
            info = await index.describe()
        except InvalidRequestError:
            checks.append(
                Check(f"index {name}", "ok", "not created yet; `hardpoint ingest run` creates it")
            )
            continue
        except HardpointError as exc:
            checks.append(
                Check(f"index {name}", "fail", f"unreachable: {exc.message}", exc.remedy or "")
            )
            continue
        checks.append(Check(f"index {name}", "ok", f"reachable, {info.count or 0} records"))

        if res.embedder_ is None:
            continue
        width = res.embedder_.dimensions
        meta = await res.state.index_meta(name)
        recorded = [
            (where, dims)
            for where, dims in (("index", info.dimensions), ("manifest", meta and meta.dimensions))
            if dims and dims != width
        ]
        if recorded:
            where, dims = recorded[0]
            checks.append(
                Check(
                    f"dimensions {name}",
                    "fail",
                    f"the {where} holds {dims}-dimension vectors; "
                    f"{res.embedder_.id!r} produces {width}",
                    f"Configure an embedding model with {dims} dimensions, or create a new "
                    f"index and re-ingest. An index cannot hold vectors of two widths.",
                )
            )
        else:
            checks.append(Check(f"dimensions {name}", "ok", f"{width} dimensions"))

    for name in sorted(config.sources):
        try:
            await build_source(res, name)
        except HardpointError as exc:
            checks.append(Check(f"source {name}", "fail", exc.message, exc.remedy or ""))
        else:
            checks.append(Check(f"source {name}", "ok"))

    try:
        pipeline = load_pipeline(res)
    except HardpointError as exc:
        checks.append(Check("pipeline", "fail", exc.message, exc.remedy or ""))
    else:
        checks.append(Check("pipeline", "ok", f"{pipeline.name!r}, {len(pipeline.steps)} steps"))
    return checks


async def _provider_checks(res: Resources) -> list[Check]:
    """Spend one tiny call per provider, to prove credentials work. ``--live`` only."""
    checks: list[Check] = []
    ctx = res.run_context()
    probes: list[tuple[str, Any]] = []
    if res.embedder_ is not None:
        probes.append(("embeddings", lambda: res.embedder.embed(["doctor"], "query", ctx)))
    if res.llm_ is not None:
        from hardpoint.core.ports import GenerationRequest, Message  # noqa: PLC0415

        request = GenerationRequest(
            messages=(Message(role="user", content="Reply with OK."),), max_output_tokens=4
        )
        probes.append(("llm", lambda: res.llm.generate(request, ctx)))
    for role, probe in probes:
        try:
            await probe()
        except HardpointError as exc:
            checks.append(Check(f"provider {role}", "fail", exc.message, exc.remedy or ""))
        else:
            checks.append(Check(f"provider {role}", "ok", "credentials accepted"))
    return checks


async def run_doctor(
    state: CliState,
    *,
    registry: ComponentRegistry | None = None,
    environ: Mapping[str, str] | None = None,
    live: bool = False,
) -> list[Check]:
    """Run every check. Never raises for a problem it was looking for.

    Args:
        state: The CLI options (environment, config directory).
        registry: Where components resolve. Injectable for tests.
        environ: The environment. Defaults to the process's over ``.env``.
        live: Also make one small call per provider to prove credentials.

    Returns:
        The checks, in the order they ran.
    """
    checks = _secret_hygiene(Path(state.config_dir))

    try:
        resolved: ResolvedConfig = load_project_config(state, environ=environ)
    except MissingEnvironmentVariableError as exc:
        return [
            *checks,
            Check(f"environment {exc.variable}", "fail", exc.message, exc.remedy or ""),
        ]
    except ConfigError as exc:
        return [*checks, Check("configuration", "fail", exc.message, exc.remedy or "")]

    checks.append(Check("configuration", "ok", f"env {resolved.snapshot.env!r}"))
    checks.append(_version_skew(resolved.config))

    registry = registry or ComponentRegistry()
    resolved_components = component_checks(resolved.config, registry)
    checks.extend(resolved_components)
    if any(check.status == "fail" for check in resolved_components):
        return checks

    try:
        res = await build_resources(resolved, registry=registry)
    except HardpointError as exc:
        return [*checks, Check("construction", "fail", exc.message, exc.remedy or "")]

    try:
        checks.extend(await _live_checks(res))
        if live:
            checks.extend(await _provider_checks(res))
    finally:
        await res.aclose()
    return checks


def render_checks(checks: list[Check]) -> str:
    """Render the report. ASCII markers, so a legacy Windows console can print it."""
    marker = {"ok": "[ ok ]", "warn": "[warn]", "fail": "[FAIL]"}
    lines: list[str] = []
    for check in checks:
        first, *rest = check.detail.splitlines() or [""]
        lines.append(f"{marker[check.status]} {check.name}" + (f": {first}" if first else ""))
        lines.extend(f"       {extra}" for extra in rest)
        if check.remedy and check.status != "ok":
            lines.extend(f"       fix: {line}" for line in check.remedy.splitlines())
    failed = sum(check.status == "fail" for check in checks)
    warned = sum(check.status == "warn" for check in checks)
    lines.append("")
    lines.append(f"{failed} failed, {warned} warnings, {len(checks) - failed - warned} ok")
    return "\n".join(lines)
