"""Contracts, data models, errors, configuration, identity and the registry.

``core`` is the foundation every other layer is written against. It owns the
port Protocols, the Pydantic data models that cross every boundary, the error
taxonomy, ``RunContext``, configuration loading and validation, the component
registry, and deterministic id and hash derivation.

It owns no I/O, no provider knowledge and no execution. It imports nothing from
``hardpoint`` outside ``core``, and its third-party surface is limited to
``pydantic``, ``anyio`` and the standard library (ARCHITECTURE.md §8.1 R1,
enforced by the "core is independent" import-linter contract).

Everything re-exported here is public API. Anything else in ``core`` is internal
and may change in a minor release (ARCHITECTURE.md §24).
"""

from __future__ import annotations

from hardpoint.core.capabilities import ALL_FILTER_OPS, IndexCapabilities, ModelCapabilities
from hardpoint.core.config import (
    CONFIG_VERSION,
    REDACTED,
    ComponentSpec,
    ConfigSnapshot,
    HardpointConfig,
    Layer,
    ResolvedConfig,
    load_config,
    resolve,
)
from hardpoint.core.context import Budget, CacheHandle, Deadline, RunContext, UsageAccumulator
from hardpoint.core.errors import (
    AuthError,
    BudgetExceeded,
    CapabilityError,
    ConfigError,
    ContractError,
    DuplicateComponentError,
    GuardViolation,
    HardpointError,
    HardpointWarning,
    IngestionError,
    InvalidConfigError,
    InvalidRequestError,
    LoopLimitExceeded,
    MissingDependencyError,
    MissingEnvironmentVariableError,
    ProviderError,
    ProviderTimeout,
    RateLimitedError,
    RetrievalError,
    TransientError,
    UnknownComponentError,
    UnsupportedFilterError,
)
from hardpoint.core.filters import (
    COMPARISON_OPS,
    STRUCTURAL_OPS,
    And,
    Comparison,
    ComparisonOp,
    Exists,
    F,
    Filter,
    FilterOp,
    Not,
    Or,
    matches,
    validate_supported,
)
from hardpoint.core.ids import (
    chunk_id,
    content_hash,
    document_id,
    normalise_text,
    stable_hash,
    text_hash,
)
from hardpoint.core.models import (
    Answer,
    Block,
    CharSpan,
    Chunk,
    Citation,
    ContextBundle,
    ContextItem,
    Degradation,
    Document,
    DropRecord,
    ParsedDocument,
    RetrievedChunk,
    RunManifest,
    StepUsage,
    TrustLevel,
    Usage,
)
from hardpoint.core.ports import (
    BlobStore,
    CacheBackend,
    Chunker,
    DocumentParser,
    EmbeddingModel,
    EmbedResult,
    GenerationDelta,
    GenerationRequest,
    GenerationResult,
    IndexInfo,
    IndexRecord,
    IndexSpec,
    LanguageModel,
    Message,
    MetadataFilter,
    MetricSink,
    PromptStore,
    RenderedPrompt,
    Reranker,
    ScoredRecord,
    SourceBlob,
    SourceEntry,
    Span,
    StateStore,
    Tool,
    ToolCall,
    ToolPermissions,
    ToolResult,
    ToolSpec,
    Tracer,
    VectorIndex,
    VectorQuery,
)
from hardpoint.core.registry import BuiltinEntry, ComponentRegistry, Kind, Registration
from hardpoint.core.types import CONTRACT_VERSION, JsonValue, ModelId, RunId

__all__ = [
    "ALL_FILTER_OPS",
    "COMPARISON_OPS",
    "CONFIG_VERSION",
    "CONTRACT_VERSION",
    "REDACTED",
    "STRUCTURAL_OPS",
    "And",
    "Answer",
    "AuthError",
    "BlobStore",
    "Block",
    "Budget",
    "BudgetExceeded",
    "BuiltinEntry",
    "CacheBackend",
    "CacheHandle",
    "CapabilityError",
    "CharSpan",
    "Chunk",
    "Chunker",
    "Citation",
    "Comparison",
    "ComparisonOp",
    "ComponentRegistry",
    "ComponentSpec",
    "ConfigError",
    "ConfigSnapshot",
    "ContextBundle",
    "ContextItem",
    "ContractError",
    "Deadline",
    "Degradation",
    "Document",
    "DocumentParser",
    "DropRecord",
    "DuplicateComponentError",
    "EmbedResult",
    "EmbeddingModel",
    "Exists",
    "F",
    "Filter",
    "FilterOp",
    "GenerationDelta",
    "GenerationRequest",
    "GenerationResult",
    "GuardViolation",
    "HardpointConfig",
    "HardpointError",
    "HardpointWarning",
    "IndexCapabilities",
    "IndexInfo",
    "IndexRecord",
    "IndexSpec",
    "IngestionError",
    "InvalidConfigError",
    "InvalidRequestError",
    "JsonValue",
    "Kind",
    "LanguageModel",
    "Layer",
    "LoopLimitExceeded",
    "Message",
    "MetadataFilter",
    "MetricSink",
    "MissingDependencyError",
    "MissingEnvironmentVariableError",
    "ModelCapabilities",
    "ModelId",
    "Not",
    "Or",
    "ParsedDocument",
    "PromptStore",
    "ProviderError",
    "ProviderTimeout",
    "RateLimitedError",
    "Registration",
    "RenderedPrompt",
    "Reranker",
    "ResolvedConfig",
    "RetrievalError",
    "RetrievedChunk",
    "RunContext",
    "RunId",
    "RunManifest",
    "ScoredRecord",
    "SourceBlob",
    "SourceEntry",
    "Span",
    "StateStore",
    "StepUsage",
    "Tool",
    "ToolCall",
    "ToolPermissions",
    "ToolResult",
    "ToolSpec",
    "Tracer",
    "TransientError",
    "TrustLevel",
    "UnknownComponentError",
    "UnsupportedFilterError",
    "Usage",
    "UsageAccumulator",
    "VectorIndex",
    "VectorQuery",
    "chunk_id",
    "content_hash",
    "document_id",
    "load_config",
    "matches",
    "normalise_text",
    "resolve",
    "stable_hash",
    "text_hash",
    "validate_supported",
]
