"""Enforce the per-package coverage floors from INSTRUCTIONS.md §12.2.

``pytest --cov`` can only express one global floor. This script reads
``coverage.xml`` and applies a floor per path prefix, so that ``core`` can be
held to 90% while the overall project floor is 85%.

Floors for packages that do not exist yet are reported as pending rather than
silently skipped, so that a package cannot quietly escape its floor by being
absent from the report.

Exits non-zero on any breach. Run from the repository root.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

# (path prefix relative to src/, minimum percentage). INSTRUCTIONS.md §12.2.
FLOORS: tuple[tuple[str, float], ...] = (
    ("hardpoint/core", 90.0),
    ("hardpoint/runtime", 90.0),
    ("hardpoint/ingestion/sync.py", 90.0),
    ("hardpoint", 85.0),
)

COVERAGE_XML = Path("coverage.xml")


@dataclass
class Tally:
    """Statement counts accumulated for one floor."""

    covered: int = 0
    total: int = 0

    @property
    def percent(self) -> float:
        """Percentage of statements covered, or 100.0 when nothing is measured."""
        return 100.0 if self.total == 0 else 100.0 * self.covered / self.total


def _measured_files(root: ET.Element) -> dict[str, Tally]:
    """Return a per-file statement tally keyed by POSIX-style source path."""
    files: dict[str, Tally] = {}
    for cls in root.iter("class"):
        filename = cls.get("filename")
        if filename is None:
            continue
        # Normalise separators and drop the layout prefix so that a floor can be
        # written as "hardpoint/core" regardless of how coverage rooted the run.
        key = filename.replace("\\", "/").removeprefix("./").removeprefix("src/")
        tally = files.setdefault(key, Tally())
        for line in cls.iter("line"):
            if line.get("branch") == "true" and line.get("condition-coverage") is None:
                continue
            tally.total += 1
            if line.get("hits", "0") != "0":
                tally.covered += 1
    return files


def main() -> int:
    """Check every floor and print a table. Returns a process exit code."""
    if not COVERAGE_XML.exists():
        sys.stderr.write(f"{COVERAGE_XML} not found. Run pytest with --cov-report=xml first.\n")
        return 2

    # S314: coverage.xml is generated by this repository's own pytest run,
    # not untrusted input, so defusedxml is not warranted in a dev script.
    files = _measured_files(ET.parse(COVERAGE_XML).getroot())  # noqa: S314

    failures: list[str] = []
    rows: list[str] = []
    for prefix, floor in FLOORS:
        tally = Tally()
        for path, file_tally in files.items():
            if path == prefix or path.startswith(prefix.rstrip("/") + "/"):
                tally.covered += file_tally.covered
                tally.total += file_tally.total

        if tally.total == 0:
            rows.append(f"  {prefix:<32} {'pending':>9}  (not built yet, floor {floor:.0f}%)")
            continue

        status = "ok" if tally.percent >= floor else "FAIL"
        rows.append(
            f"  {prefix:<32} {tally.percent:>8.2f}%  floor {floor:.0f}%  "
            f"({tally.covered}/{tally.total})  {status}"
        )
        if tally.percent < floor:
            failures.append(
                f"{prefix}: {tally.percent:.2f}% is below the {floor:.0f}% floor "
                f"({tally.covered}/{tally.total} statements)"
            )

    sys.stdout.write("Coverage floors (INSTRUCTIONS.md 12.2)\n")
    sys.stdout.write("\n".join(rows) + "\n")

    if failures:
        sys.stderr.write("\nCoverage floor breached:\n")
        for failure in failures:
            sys.stderr.write(f"  - {failure}\n")
        return 1

    sys.stdout.write("\nAll floors met.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
